require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe BillsController do

  def mock_bill(stubs={})
    @mock_bill ||= mock_model(Bill, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all bills as @bills" do
      Bill.stub(:all) { [mock_bill] }
      get :index
      assigns(:bills).should eq([mock_bill])
    end
  end

  describe "GET show" do
    it "assigns the requested bill as @bill" do
      Bill.stub(:find).with("37") { mock_bill }
      get :show, :id => "37"
      assigns(:bill).should be(mock_bill)
    end
  end

  describe "GET new" do
    it "assigns a new bill as @bill" do
      Bill.stub(:new) { mock_bill }
      get :new
      assigns(:bill).should be(mock_bill)
    end
  end

  describe "GET edit" do
    it "assigns the requested bill as @bill" do
      Bill.stub(:find).with("37") { mock_bill }
      get :edit, :id => "37"
      assigns(:bill).should be(mock_bill)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created bill as @bill" do
        Bill.stub(:new).with({'these' => 'params'}) { mock_bill(:save => true) }
        post :create, :bill => {'these' => 'params'}
        assigns(:bill).should be(mock_bill)
      end

      it "redirects to the created bill" do
        Bill.stub(:new) { mock_bill(:save => true) }
        post :create, :bill => {}
        response.should redirect_to(bill_url(mock_bill))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved bill as @bill" do
        Bill.stub(:new).with({'these' => 'params'}) { mock_bill(:save => false) }
        post :create, :bill => {'these' => 'params'}
        assigns(:bill).should be(mock_bill)
      end

      it "re-renders the 'new' template" do
        Bill.stub(:new) { mock_bill(:save => false) }
        post :create, :bill => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested bill" do
        Bill.stub(:find).with("37") { mock_bill }
        mock_bill.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :bill => {'these' => 'params'}
      end

      it "assigns the requested bill as @bill" do
        Bill.stub(:find) { mock_bill(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:bill).should be(mock_bill)
      end

      it "redirects to the bill" do
        Bill.stub(:find) { mock_bill(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(bill_url(mock_bill))
      end
    end

    describe "with invalid params" do
      it "assigns the bill as @bill" do
        Bill.stub(:find) { mock_bill(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:bill).should be(mock_bill)
      end

      it "re-renders the 'edit' template" do
        Bill.stub(:find) { mock_bill(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested bill" do
      Bill.stub(:find).with("37") { mock_bill }
      mock_bill.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the bills list" do
      Bill.stub(:find) { mock_bill }
      delete :destroy, :id => "1"
      response.should redirect_to(bills_url)
    end
  end

end
