require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by the Rails when you ran the scaffold generator.

describe MetropolisController do

  def mock_metropoli(stubs={})
    @mock_metropoli ||= mock_model(Metropoli, stubs).as_null_object
  end

  describe "GET index" do
    it "assigns all metropolis as @metropolis" do
      Metropoli.stub(:all) { [mock_metropoli] }
      get :index
      assigns(:metropolis).should eq([mock_metropoli])
    end
  end

  describe "GET show" do
    it "assigns the requested metropoli as @metropoli" do
      Metropoli.stub(:find).with("37") { mock_metropoli }
      get :show, :id => "37"
      assigns(:metropoli).should be(mock_metropoli)
    end
  end

  describe "GET new" do
    it "assigns a new metropoli as @metropoli" do
      Metropoli.stub(:new) { mock_metropoli }
      get :new
      assigns(:metropoli).should be(mock_metropoli)
    end
  end

  describe "GET edit" do
    it "assigns the requested metropoli as @metropoli" do
      Metropoli.stub(:find).with("37") { mock_metropoli }
      get :edit, :id => "37"
      assigns(:metropoli).should be(mock_metropoli)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "assigns a newly created metropoli as @metropoli" do
        Metropoli.stub(:new).with({'these' => 'params'}) { mock_metropoli(:save => true) }
        post :create, :metropoli => {'these' => 'params'}
        assigns(:metropoli).should be(mock_metropoli)
      end

      it "redirects to the created metropoli" do
        Metropoli.stub(:new) { mock_metropoli(:save => true) }
        post :create, :metropoli => {}
        response.should redirect_to(metropoli_url(mock_metropoli))
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved metropoli as @metropoli" do
        Metropoli.stub(:new).with({'these' => 'params'}) { mock_metropoli(:save => false) }
        post :create, :metropoli => {'these' => 'params'}
        assigns(:metropoli).should be(mock_metropoli)
      end

      it "re-renders the 'new' template" do
        Metropoli.stub(:new) { mock_metropoli(:save => false) }
        post :create, :metropoli => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested metropoli" do
        Metropoli.stub(:find).with("37") { mock_metropoli }
        mock_metropoli.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => "37", :metropoli => {'these' => 'params'}
      end

      it "assigns the requested metropoli as @metropoli" do
        Metropoli.stub(:find) { mock_metropoli(:update_attributes => true) }
        put :update, :id => "1"
        assigns(:metropoli).should be(mock_metropoli)
      end

      it "redirects to the metropoli" do
        Metropoli.stub(:find) { mock_metropoli(:update_attributes => true) }
        put :update, :id => "1"
        response.should redirect_to(metropoli_url(mock_metropoli))
      end
    end

    describe "with invalid params" do
      it "assigns the metropoli as @metropoli" do
        Metropoli.stub(:find) { mock_metropoli(:update_attributes => false) }
        put :update, :id => "1"
        assigns(:metropoli).should be(mock_metropoli)
      end

      it "re-renders the 'edit' template" do
        Metropoli.stub(:find) { mock_metropoli(:update_attributes => false) }
        put :update, :id => "1"
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested metropoli" do
      Metropoli.stub(:find).with("37") { mock_metropoli }
      mock_metropoli.should_receive(:destroy)
      delete :destroy, :id => "37"
    end

    it "redirects to the metropolis list" do
      Metropoli.stub(:find) { mock_metropoli }
      delete :destroy, :id => "1"
      response.should redirect_to(metropolis_url)
    end
  end

end
